import "./globals.css";

import ClientProvider from "./ClientProvider";
export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientProvider>
          <div className="d-flex flex-column min-vh-100">
           
            <main className="flex-grow-1 d-flex flex-column">{children}</main>
            </div>
        </ClientProvider>
      </body>
      
    </html>
  );
}
